alias ..='cd ..'
alias ...='cd ../..'
alias ls='ls --color=auto'
alias lsd='ls -r --sort=time --color=auto'

alias kali='ssh kali.local'
alias home='ssh emil@home.emibre.com'

alias emacs='emacs -nw'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'